In [1]:
import numpy as np

In [2]:
liste = [1,2,3]
tek = np.array(liste)

In [3]:
tek

array([1, 2, 3])

In [4]:
liste2 = [[10,20,30],[40,50,60],[70,80,90]]

In [5]:
cok = np.array(liste2)

In [6]:
cok

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [8]:
cok[1,1]

50

In [9]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.linspace(1,100,5)       #beş parçaya bölüyor

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [19]:
np.linspace(1,30,7)

array([ 1.        ,  5.83333333, 10.66666667, 15.5       , 20.33333333,
       25.16666667, 30.        ])

In [20]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.random.randint(0,10)      #0 ve 10 arasında rastgele bir sayı döner

7

In [29]:
np.random.randint(20)       #0 ve 20 arasında rastgele bir sayı döner

9

In [32]:
np.random.randint(1,10,5)          # 1 ve 10 arasında rastgele 5 değeri bir array e depolar

array([2, 5, 3, 9, 2])

In [34]:
np.random.randn(5)      #sıfırın eterafında pozitif ve negatif rastgele sayılar

array([-0.31665855,  0.19186444,  1.0821597 ,  1.37636347,  1.05879823])

In [35]:
deger = np.arange(25)

In [37]:
deger.reshape(5,5)          #deger arrayini 5x5 matrise ekledi

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
yenideger = np.random.randint(1,100,10)

In [39]:
yenideger

array([18, 70, 21, 69, 71,  3, 98, 14, 48, 30])

In [43]:
yenideger.max()          #en büyük değeri getirir.

98

In [44]:
yenideger.min()     #en küçük değeri getirir.

3

In [46]:
yenideger.sum()          #bütün sayıların toplamını getirir.

442

In [48]:
yenideger.mean()          #bütün sayıların ortalamasını döndürür

44.2

In [51]:
yenideger.argmax()      #en büyük sayının bulunduğu indexi verir.

6

In [53]:
yenideger.argmin()      #en küçük değerin bulunduğu indexi verir.

5

In [54]:
determinant = np.random.randint(1,100,25)

In [55]:
determinant

array([61, 46, 27, 19, 75, 58, 78, 51, 92, 43,  7, 22, 76, 24, 35, 69, 68,
        2,  2, 10, 86, 15, 29, 91, 39])

In [57]:
matris = determinant.reshape(5,5)

In [58]:
matris

array([[61, 46, 27, 19, 75],
       [58, 78, 51, 92, 43],
       [ 7, 22, 76, 24, 35],
       [69, 68,  2,  2, 10],
       [86, 15, 29, 91, 39]])

In [60]:
np.linalg.det(matris)              # determinantı hesaplar

1801006122.999997

In [62]:
array = np.array([[1,2],[3,4]])

In [63]:
array

array([[1, 2],
       [3, 4]])

In [65]:
np.linalg.det(array)

-2.0000000000000004

In [67]:
round(np.linalg.det(array))          # sayıyı integer yazar

-2

In [68]:
degis = np.arange(1,10)

In [69]:
degis

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
degis[1]

2

In [71]:
degis[8]

9

In [72]:
degis[1:7]

array([2, 3, 4, 5, 6, 7])

In [73]:
degis[:5]

array([1, 2, 3, 4, 5])

In [74]:
degis[::2]

array([1, 3, 5, 7, 9])

In [77]:
degis[:6] = 25          #ilk 6 değeri 25 yapar

In [78]:
degis

array([25, 25, 25, 25, 25, 25,  7,  8,  9])

In [79]:
degis2 = degis

In [80]:
degis2

array([25, 25, 25, 25, 25, 25,  7,  8,  9])

In [81]:
degis2[:6] = 100

In [82]:
degis2

array([100, 100, 100, 100, 100, 100,   7,   8,   9])

In [84]:
degis                          #yapılan değişiklik aynı zamanda degis i de etkiler.çünkü aynı bellek alanında oluşturuldu

array([100, 100, 100, 100, 100, 100,   7,   8,   9])

In [86]:
degis3 = degis.copy()          #bu şekilde yapılırsa aynı bellek alanında olmaz.yapılan değişiklikler birbirini etkilemez.

In [90]:
yenidegis = np.arange(1,21)

In [95]:
matris = yenidegis.reshape(5,4)

In [96]:
matris[2,3]

12

In [97]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [98]:
matris[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [99]:
matris[:3,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [100]:
matris[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [101]:
matris[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [102]:
degis = np.arange(1,20)

In [104]:
degis > 6        #6 dan küçükleri false , 6 dan büyükleri true döndürür.

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [105]:
dogrular = degis > 6

In [107]:
degis[dogrular]          #doğru olanları bastırır.

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [109]:
degis[degis > 10]      #bu şekildede kullanılır

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [111]:
degis1 = np.arange(1,10)

In [112]:
degis1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
degis2 = np.arange(10,19)

In [114]:
degis2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [116]:
degis1 + degis2

array([11, 13, 15, 17, 19, 21, 23, 25, 27])

In [117]:
degis1 - degis2

array([-9, -9, -9, -9, -9, -9, -9, -9, -9])

In [118]:
degis1 * degis2

array([ 10,  22,  36,  52,  70,  90, 112, 136, 162])

In [119]:
degis1 / degis2

array([0.1       , 0.18181818, 0.25      , 0.30769231, 0.35714286,
       0.4       , 0.4375    , 0.47058824, 0.5       ])

In [121]:
degis1 - 10   #her bir sayıdan 10 çıkarır

array([-9, -8, -7, -6, -5, -4, -3, -2, -1])

In [122]:
degis1 * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [123]:
degis1 + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [124]:
degis1 / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [126]:
np.sqrt(degis1)         #her bir elemanın karekökünü alır

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])